// <auto-generated />
using System;
using MatricConnect.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MatricConnect.Migrations
{
    [DbContext(typeof(MatricConnectContext))]
    partial class MatricConnectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.30");

            modelBuilder.Entity("MatricConnect.Models.Programme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ApplicationDeadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldOfStudy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RequiredAPS")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("RequiredMathematics")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RequiredPhysicalScience")
                        .HasColumnType("TEXT");

                    b.Property<int>("UniversityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("Programmes");
                });

            modelBuilder.Entity("MatricConnect.Models.SavedProgramme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProgrammeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProgrammeId");

                    b.HasIndex("StudentId");

                    b.ToTable("SavedProgrammes");
                });

            modelBuilder.Entity("MatricConnect.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("APSScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MathematicsMark")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PhysicalScienceMark")
                        .HasColumnType("TEXT");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("MatricConnect.Models.University", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Universities");
                });

            modelBuilder.Entity("MatricConnect.Models.Programme", b =>
                {
                    b.HasOne("MatricConnect.Models.University", "University")
                        .WithMany("Programmes")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("MatricConnect.Models.SavedProgramme", b =>
                {
                    b.HasOne("MatricConnect.Models.Programme", "Programme")
                        .WithMany("SavedProgrammes")
                        .HasForeignKey("ProgrammeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MatricConnect.Models.Student", "Student")
                        .WithMany("SavedProgrammes")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Programme");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MatricConnect.Models.Programme", b =>
                {
                    b.Navigation("SavedProgrammes");
                });

            modelBuilder.Entity("MatricConnect.Models.Student", b =>
                {
                    b.Navigation("SavedProgrammes");
                });

            modelBuilder.Entity("MatricConnect.Models.University", b =>
                {
                    b.Navigation("Programmes");
                });
#pragma warning restore 612, 618
        }
    }
}
